### ISSUE TITLE
build docs

### ISSUE THREAD

**Issue by djdanielsson** [TrifectaIII/MTG-Card-Reader-Web#16]
Is there any documentation on how people can build this themselves, instead of using your website? And is there a way for you to save the cards it has found to a database? Also have you thought about putting this in a docker container?

**Comment by TrifectaIII** [comment]
Hey man, sorry for taking so long to respond to this. I didn't see the email that github sent me. 

Building this yourself requires running `gen_set_files_gatherer.py` until all card images in each set have been downloaded and processed (this takes forever, I could get you the processed set files if you needed them in other ways), then running `bottle_app.py`. 

There is currently no way to save the cards to a database other than building a text file using the web interface and processing that yourself, but adding database functionality would be relatively trivial if you wanted to when you are running the project locally.

I have not used docker before, so I have not considered that. What benefits does docker offer compared to a VM?

**Comment by djdanielsson** [comment]
if you put it in a container then it would be a lot easier for someone to deploy a copy of it, instead of having to try and download the code and build it and configure it themselves. I haven't spent the time playing with it anymore which is why I didn't originally reply to your comment, but I am not sure if I will ever get around to it or not so thought it would be worth answering your question at least. Thanks for the info though so I should be able to get it working if I do get around to trying it again.
